"""Initial migration: add regions, cities, patients, medical_cards tables

Revision ID: ae160b08a146
Revises: 4c01a57676d7
Create Date: 2025-12-18 05:10:24.571856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae160b08a146'
down_revision: Union[str, None] = '4c01a57676d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
